"""roster_short update3

Revision ID: 12d607a9585a
Revises: f789c4b09256
Create Date: 2023-06-07 17:31:08.393582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d607a9585a'
down_revision = 'f789c4b09256'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
