"""User

Revision ID: 4b217398aa2e
Revises: ad2e1e4a9880
Create Date: 2023-05-12 10:04:18.770053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b217398aa2e'
down_revision = 'ad2e1e4a9880'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
