"""initial4

Revision ID: 5613f37f882d
Revises: 6adc337daa52
Create Date: 2022-11-01 16:30:57.879733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5613f37f882d'
down_revision = '6adc337daa52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
