"""initial4

Revision ID: 6adc337daa52
Revises: 882b835f1669
Create Date: 2022-10-31 22:39:18.767429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6adc337daa52'
down_revision = '882b835f1669'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_response_response', table_name='response')
    op.drop_index('ix_response_response_id', table_name='response')
    op.drop_table('response')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('response_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name='response_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='response_user_id_fkey'),
    sa.PrimaryKeyConstraint('response_id', name='response_pkey')
    )
    op.create_index('ix_response_response_id', 'response', ['response_id'], unique=False)
    op.create_index('ix_response_response', 'response', ['response'], unique=False)
    # ### end Alembic commands ###
