"""roster_short update4

Revision ID: 8499fa34dc9c
Revises: a161ab8c917f
Create Date: 2023-06-10 08:27:12.526641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8499fa34dc9c'
down_revision = 'a161ab8c917f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roster_short', sa.Column('roster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roster_short', 'rosters', ['roster_id'], ['roster_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roster_short', type_='foreignkey')
    op.drop_column('roster_short', 'roster_id')
    # ### end Alembic commands ###
