"""initial3

Revision ID: 882b835f1669
Revises: ff57dae93cae
Create Date: 2022-10-31 22:15:48.724524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882b835f1669'
down_revision = 'ff57dae93cae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rosters', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('rosters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rosters', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rosters', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rosters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('rosters', 'created_at')
    # ### end Alembic commands ###
