"""initial6

Revision ID: 8a0c5d430ab1
Revises: a8e50206cb4c
Create Date: 2022-11-04 21:22:32.342740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0c5d430ab1'
down_revision = 'a8e50206cb4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nationality', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_nationality'), 'users', ['nationality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nationality'), table_name='users')
    op.drop_column('users', 'nationality')
    # ### end Alembic commands ###
