"""roster_short

Revision ID: 8b08745858f5
Revises: 7b4a25c87802
Create Date: 2023-06-07 16:39:37.937040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b08745858f5'
down_revision = '7b4a25c87802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
