"""unavail uuid

Revision ID: a13519bd9411
Revises: de64afe0c347
Create Date: 2023-06-04 21:42:50.789273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13519bd9411'
down_revision = 'de64afe0c347'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
