"""roster_short update3

Revision ID: a161ab8c917f
Revises: bd69e8b549a0
Create Date: 2023-06-08 23:59:07.481592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a161ab8c917f'
down_revision = 'bd69e8b549a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roster_short', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'roster_short', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roster_short', type_='foreignkey')
    op.drop_column('roster_short', 'user_id')
    # ### end Alembic commands ###
