"""initial5

Revision ID: a8e50206cb4c
Revises: 5613f37f882d
Create Date: 2022-11-04 21:17:25.782574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e50206cb4c'
down_revision = '5613f37f882d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_country_code'), 'users', ['country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_country_code'), table_name='users')
    op.drop_column('users', 'country_code')
    # ### end Alembic commands ###
