"""User

Revision ID: ad2e1e4a9880
Revises: 4b1db1b6c8a6
Create Date: 2023-05-12 00:44:21.483798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2e1e4a9880'
down_revision = '4b1db1b6c8a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.String(), nullable=False))
    op.drop_column('users', 'fastname')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('fastname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###
