"""roster_short update

Revision ID: bd69e8b549a0
Revises: 12d607a9585a
Create Date: 2023-06-08 20:00:24.864610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd69e8b549a0'
down_revision = '12d607a9585a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_short',
    sa.Column('rostershort_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('event_date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('rostershort_id')
    )
    op.create_index(op.f('ix_roster_short_rostershort_id'), 'roster_short', ['rostershort_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_short_rostershort_id'), table_name='roster_short')
    op.drop_table('roster_short')
    # ### end Alembic commands ###
