"""userrole_id

Revision ID: c5ef0a65a925
Revises: 8499fa34dc9c
Create Date: 2023-06-10 09:58:21.700832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ef0a65a925'
down_revision = '8499fa34dc9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rosters_userrole_id', table_name='rosters')
    op.create_index(op.f('ix_rosters_userrole_id'), 'rosters', ['userrole_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rosters_userrole_id'), table_name='rosters')
    op.create_index('ix_rosters_userrole_id', 'rosters', ['userrole_id'], unique=False)
    # ### end Alembic commands ###
