"""User

Revision ID: cacbf30e7e95
Revises: fece060b1c7d
Create Date: 2023-05-12 00:30:42.007504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacbf30e7e95'
down_revision = 'fece060b1c7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unavailabilities', sa.Column('reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_unavailabilities_reason'), 'unavailabilities', ['reason'], unique=False)
    op.drop_column('users', 'country_of_residence')
    op.drop_column('users', 'nationality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('country_of_residence', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_unavailabilities_reason'), table_name='unavailabilities')
    op.drop_column('unavailabilities', 'reason')
    # ### end Alembic commands ###
