"""User

Revision ID: ddc5ecfb9d42
Revises: cacbf30e7e95
Create Date: 2023-05-12 00:40:55.137088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc5ecfb9d42'
down_revision = 'cacbf30e7e95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('fastname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('d_o_b', sa.Date(), nullable=False))
    op.drop_column('users', 'Lastname')
    op.drop_column('users', 'Firstname')
    op.drop_column('users', 'D_O_B')
    op.drop_column('users', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('D_O_B', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('Firstname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('Lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'd_o_b')
    op.drop_column('users', 'fastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
