"""unavail

Revision ID: de64afe0c347
Revises: cf95c3bff9a6
Create Date: 2023-06-02 14:16:43.123690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de64afe0c347'
down_revision = 'cf95c3bff9a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unavailabilities', sa.Column('startdate', sa.Date(), nullable=True))
    op.add_column('unavailabilities', sa.Column('enddate', sa.Date(), nullable=True))
    op.drop_index('ix_unavailabilities_end_date', table_name='unavailabilities')
    op.drop_index('ix_unavailabilities_start_date', table_name='unavailabilities')
    op.create_index(op.f('ix_unavailabilities_enddate'), 'unavailabilities', ['enddate'], unique=False)
    op.create_index(op.f('ix_unavailabilities_startdate'), 'unavailabilities', ['startdate'], unique=False)
    op.drop_column('unavailabilities', 'end_date')
    op.drop_column('unavailabilities', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unavailabilities', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('unavailabilities', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_unavailabilities_startdate'), table_name='unavailabilities')
    op.drop_index(op.f('ix_unavailabilities_enddate'), table_name='unavailabilities')
    op.create_index('ix_unavailabilities_start_date', 'unavailabilities', ['start_date'], unique=False)
    op.create_index('ix_unavailabilities_end_date', 'unavailabilities', ['end_date'], unique=False)
    op.drop_column('unavailabilities', 'enddate')
    op.drop_column('unavailabilities', 'startdate')
    # ### end Alembic commands ###
