"""roster_short update2

Revision ID: f789c4b09256
Revises: 19a2320f1524
Create Date: 2023-06-07 17:28:26.880353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f789c4b09256'
down_revision = '19a2320f1524'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
