"""initial

Revision ID: 0457423a22b1
Revises: 909ee96def4d
Create Date: 2022-10-25 23:39:41.338308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0457423a22b1'
down_revision = '909ee96def4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_user_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_user_id_fkey', 'events', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
